# SearchParams:
domains: ['theage', 'theaustralian', 'couriermail', 'dailytelegraph', 'smh', 'thewest', 'watoday', 'heraldsun']
query: '*'
date_from: '2024-03-01'
date_to: '2024-03-03'

country: 'au'  #au/de
language: 'en'  #en/de

# Google BigQuery Params
project_name: 'dmrc-data'
dataset_name: 'newsdataio_2024'
tablename: 'newsdata_nov2023_au'
